- name: Create cache table
  shell: "{{ ansistrano_shared_path }}/venv/bin/python {{ ansistrano_release_path.stdout }}/src/manage.py createcachetable"

- name: Collect static
  shell: "{{ ansistrano_shared_path }}/venv/bin/python {{ ansistrano_release_path.stdout }}/src/manage.py collectstatic --noinput"

- name: Restart uWSGI
  service:
    name: uwsgi
    state: restarted

- name: Restart PM2 app
  shell: "pm2 restart {{ project_slug }}"

- name: Restart Nginx
  service:
    name: nginx
    state: restarted

