version: "3.1"
services:
  web:
    image: nginx:alpine
    working_dir: /app
    ports:
      - "8081:80"
      - "8082:443"
    links:
      - python
    volumes:
      - "./docker/files/config/nginx.conf.template:/etc/nginx/templates/default.conf.template:cached"
      - "./src/media:/app/media"
      - "./src/static:/app/static"
    environment:
      - PYTHON_HOST=http://python

  python:
    image: frojd/company_project_python
    build: ./src
    volumes:
      - "./src:/app"
    depends_on:
      - db
    env_file: ./docker/config/python.env

  db:
    image: postgis/postgis:12-2.5-alpine
    ports:
      - "8083:5432"
    volumes:
      - "./docker/files/db-dumps/:/docker-entrypoint-initdb.d/"
      - "./docker/files/shared:/shared:rw"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
